---
kind: Template
apiVersion: v1
metadata:
  name: jenkins-pipeline-no-ocp-triggers
objects:
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: "${ROLE}"
  roleRef:
    name: "${ROLE}"                               
  subjects:
  - kind: Group
    name: "${GROUP}"
parameters:    
- name: ROLE
  displayName: Role
  description: The role to bind to the group
  required: true
- name: GROUP
  displayName: Group
  description: The group to bind to the role
  required: true  