---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/../params/projectrequests/ci-cd"
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/../params/projectrequests/dev"
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/../params/projectrequests/demo"
    tags:
    - projects
- object: ci-cd-builds
  content:
  - name: jenkins-s2i
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-s2i-build/template.json"
    params: "{{ inventory_dir }}/../params/jenkins/build"
    namespace: jenkins-42276-ci-cd
    tags:
    - jenkins
  - name: mvn-jenkins-slave
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/mvn-jenkins-slave/build"
    namespace: jenkins-42276-ci-cd
    tags:
    - jenkins-slaves
- object: ci-cd-deployments
  content:
  - name: jenkins-ephemeral
    template: openshift//jenkins-ephemeral
    params: "{{ inventory_dir }}/../params/jenkins/deploy"
    namespace: jenkins-42276-ci-cd
    tags:
    - jenkins
  - name: nexus
    template: "{{ inventory_dir }}/../openshift-templates/nexus/template.json"
    params: "{{ inventory_dir }}/../params/nexus/deploy"
    namespace: jenkins-42276-ci-cd
    tags:
    - nexus 
- object: app-builds
  content:
  - name: java-app-build
    template: "{{ inventory_dir }}/../openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/../params/java-app/build"    
    namespace: jenkins-42276-ci-cd
- object: dev-stage
  content:
  - name: java-app
    template: "{{ inventory_dir }}/../openshift-templates/automation-api-hsql/template.json"
    params: "{{ inventory_dir }}/../params/java-app/deploy_dev"
    namespace: jenkins-42276-dev
    tags:
    - java-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/java-app/fabric8_dev"
    namespace: jenkins-42276-dev
    tags:
    - java-app
- object: demo-stage
  content:
  - name: java-app
    template: "{{ inventory_dir }}/../openshift-templates/automation-api-hsql/template.json"
    params: "{{ inventory_dir }}/../params/java-app/deploy_demo"
    namespace: jenkins-42276-demo
    tags:
    - java-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/java-app/fabric8_demo"
    namespace: jenkins-42276-demo
    tags:
    - java-app  